apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedroguedes-playlist-generator-api-deployment
  namespace: pedroguedes
  labels:
    app: playlist-generator-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist-generator-api
  template:
    metadata:
      labels:
        app: playlist-generator-api
    spec:
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: project2-pv2-pedroguedes
      containers:
        - name: playlist-generator-api
          image:  pedroufmg/playlist-generator-api:latest
          volumeMounts:
            - name: persistent-volume
              mountPath: /app/data
          ports:
          - containerPort: 7777
