apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedroguedes-playlist-generator-api-deployment
  namespace: pedroguedes
  labels:
    app: pedro-playlist-generator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedro-playlist-generator-api
  template:
    metadata:
      labels:
        app: pedro-playlist-generator-api
    spec:
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: project2-pv2-pedroguedes
      containers:
        - name: pedro-playlist-generator-api
          image:  pedroufmg/playlist-generator-api:0.4
          volumeMounts:
            - name: persistent-volume
              mountPath: /app/data
          ports:
          - containerPort: 52055
          env:
            - name: API_VERSION
              value: "0.4"
      imagePullSecrets:
        - name: regcred
