apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-pedroguedes
  namespace: pedroguedes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class-pedroguedes