apiVersion: v1
kind: Service
metadata:
  name: playlist-generator-api-service
spec:
  type: LoadBalancer
  selector:
    app: pedro-playlist-generator-api
  ports:
    - protocol: TCP
      port: 52055
      targetPort: 7777
