apiVersion: v1
kind: Service
metadata:
  name: pedroguedes-playlist-generator-api-service
  namespace: pedroguedes
spec:
  type: NodePort
  selector:
    app: pedro-playlist-generator-api
  ports:
    - protocol: TCP
      port: 52055
      targetPort: 52055
      nodePort: 52055
      externalTrafficPolicy: Cluster
